# Generated by Django 4.2.2 on 2023-08-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhs_reg_number', models.CharField(max_length=20, verbose_name='NHS Registration Number')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post Code')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('time_occurred', models.DateTimeField(blank=True, null=True, verbose_name='Time Occurred')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('action_taken', models.CharField(blank=True, max_length=50, null=True, verbose_name='Action Taken')),
                ('minutes_on_call', models.IntegerField(verbose_name='Minutes on Call')),
                ('signed_off', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'db_table': 'Incident',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhs_reg_number', models.CharField(max_length=20, verbose_name='NHS Registration Number')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post Code')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='RescueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='record.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='record.patient')),
            ],
            options={
                'verbose_name_plural': 'Rescue Requests',
                'db_table': 'RescueRequest',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('treatment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Treatment')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='record.incident')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='record.patient')),
            ],
            options={
                'verbose_name_plural': 'Medical Records',
                'db_table': 'MedicalRecord',
            },
        ),
    ]
