# Generated by Django 4.2.4 on 2023-08-15 10:24

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_hospital_location_incident_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [-3.2141745, 55.933486], 'marker_color': 'blue'}, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [-3.2141745, 55.933486], 'marker_color': 'blue'}, null=True),
        ),
    ]
