# Generated by Django 4.2.4 on 2023-08-15 10:36

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_hospital_latitude_remove_hospital_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='address',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='post_code',
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, default=[-3.2141745, 55.933486], map_attrs={'center': [-3.2141745, 55.933486], 'marker_color': 'blue'}, null=True),
        ),
    ]
