# Generated by Django 4.2.4 on 2023-08-17 12:46

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_incident_address_remove_incident_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, default=[-3.2141745, 55.933486], map_attrs={'center': [-3.2141745, 55.933486], 'marker_color': 'blue'}, null=True),
        ),
    ]
